### ISSUE TITLE
Error with weapons like staffs that have 5 attack styles

### ISSUE THREAD

**Issue by zeakzz** [BegOsrs/Ba-minigame#7]
2021-05-05 19:28:17 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at begosrs.barbarianassault.BaMinigamePlugin.restoreAttackStyleText(BaMinigamePlugin.java:804)
	at begosrs.barbarianassault.BaMinigamePlugin.updateAttackStyleText(BaMinigamePlugin.java:665)
	at begosrs.barbarianassault.BaMinigamePlugin.lambda$onScriptPostFired$2(BaMinigamePlugin.java:568)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:79)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at client.zn(client.java:40697)
	at client.aj(client.java)
	at al.zw(al.java:365)
	at al.run(al.java:319)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by BegOsrs** [comment]
Which staff is it?
